# Generated by Django 5.1.7 on 2025-04-05 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_userprofile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.hostel')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'warden'}, on_delete=django.db.models.deletion.CASCADE, related_name='warden_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
