# Generated by Django 5.1.7 on 2025-04-04 18:30

from django.db import migrations

def fix_null_users(apps, schema_editor):
    Complaint = apps.get_model('ssdash', 'Complaint')
    User = apps.get_model('accounts', 'CustomUser')
    
    # Assign complaints without users to admin (or delete them)
    admin = User.objects.filter(is_superuser=True).first()
    if admin:
        Complaint.objects.filter(user__isnull=True).update(user=admin)


class Migration(migrations.Migration):

    dependencies = [
        ('ssdash', '0003_alter_complaint_roll_number_alter_complaint_user'),
    ]

    operations = [
        migrations.RunPython(fix_null_users),
    ]
