# Generated by Django 5.1.2 on 2025-03-24 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be in format: YYYY_group_XXXX', regex='^(2021|2022|2023|2024)_(bcs|bcd|bcy|bec)_\\d{4}$')]),
        ),
    ]
