# Generated by Django 5.1.7 on 2025-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_complainttype_remove_workerprofile_assigned_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='worker_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning Staff'), ('itsupport', 'IT Support Staff')], max_length=20),
        ),
    ]
